### ISSUE TITLE
🎨 App Layout - Create Website Footer

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website-html#8]
#  Create the website footer
---
Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)
---

### Summary

As a user, I want a simple footer that displays my information in a structured way.

### Description

Currently, the website page has no footer. Your job is to add one. The footer needs to appear well on the web and mobile:

Web:

![dynamic footer](https://github.com/italanta/elewa-website/assets/20738858/2b793713-5c98-4a46-b44c-d2e178b31cf6)

Mobile:

![dynamic footer mobile](https://github.com/italanta/elewa-website/assets/20738858/42969dfb-ec0e-4199-a755-15ad8d02dd0f)

NB: The mobile design is for a different website, ours should look exactly the same apart from the textual content itself

---
Link to full design:

```
https://xd.adobe.com/view/30f592fb-2ceb-4ea9-a6b9-2aee6239a957-65a6/screen/9ce6f3d4-3ff5-4c36-86f0-bf3a67e02b13
```

### Technical Analysis

Create a footer.html file in `src/elements/layout/footer/footer.html`

### Assets.

Logo URL
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1695970671/elewa-education-website/Shared/elewa-logo_eocvkz.png
```
Right Arrow URL
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1695972080/elewa-education-website/Shared/toRightArrow_tlcdnk.svg
```

#### Social media links

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690295/elewa-group-website/Icons/SVG/_Social/instagram_x8ujcq.svg

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690294/elewa-group-website/Icons/SVG/_Social/linkedin_x8smhm.svg

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690294/elewa-group-website/Icons/SVG/_Social/facebook_lhhwk2.svg

### Acceptance Criteria

- [ ] When rendered the component is pixel perfect compared to the design above.
- [ ] The code is isolated to the src/elements/layout/footer package, unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone

**Comment by winniegithubrit** [comment]
working on this
